# Python  CircleCI 2.1 config file
version: 2.1

jobs:
  build:
    docker:
        - image: circleci/python:3.7
    
    working_directory: ~/repo

    steps:
      # Step 1: Obtain repo from github
      - checkout
      # Step 2: Create Virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv calc
            . calc/bin/activate
            pip install -r requierments.txt
      # Step 3: Run linter and pytest with code coverage
      - run:
          name: run tests
          command: |
            flake8 --exclude=calc* --statistics
            pytest -v --cov=calculator    
